core/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, register, verify, validate_username, PostView, logout_user
from . import views
from django.contrib.auth import views as auth_views

app_name = "core"

urlpatterns = [
    path('',views.index,name="index"),
    path('register/',views.register,name="register"),
    path('verify/', views.verify, name='verify'),
    path('post/<str:slug>/',views.PostView.as_view(),name="post"),
    path('logout/',views.logout_user,name='logout'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html'),name='login'),
    path('ajax/validate_username/',views.validate_username,name='validate_username'),
]

magazine/urls.py
from django.contrib import admin
from django.urls import path,include
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('',views.index,name="index"),
    path('accounts/', include('allauth.urls')),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
import uuid

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    content = models.TextField()
    slug = models.SlugField(default="",editable=False,unique=True,max_length=8)
    def get_slug(self):
        uuid_value = str(uuid.uuid4())
        unq_slug = slugify(uuid_value[0:6])
        return unq_slug
    def __str__(self):
        return self.title

    def save(self,*args,**kwargs):
        self.slug = self.get_slug()
        super().save(*args,**kwargs)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,max_length=30)
    writer = models.BooleanField(default=False)
    verified = models.BooleanField(default=False)
    activation_key = models.SlugField(default="",editable=False,max_length=15,unique=True)

    def get_slug(self):
        uuid_value = str(uuid.uuid4())
        unique_slug = slugify(uuid_value[0:12])
        return unique_slug

    def __str__(self):
        return f'{self.user.username}'

    def save(self, *args, **kwargs):
        self.activation_key = self.get_slug()
        super().save(*args, **kwargs)

from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import signals

@receiver(post_save,sender=User)
def save_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)
    else:
        instance.profile.save()

def delete_user(sender, instance=None, **kwargs):
    try:
        instance.user
    except User.DoesNotExist:
        pass
    else:
        instance.user.delete()
signals.post_delete.connect(delete_user, sender=Profile)

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ProfileForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(
        attrs = {
            'type' : 'email',
            'placeholder' : ('Email')
        }
    ))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name'}),
            'email': forms.TextInput(attrs={'placeholder': 'Email'}),
        }

    def clean(self):
        cleaned_data = super(ProfileForm,self).clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        email = cleaned_data.get('email')

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ProfileForm
from django.contrib.auth import authenticate, login, logout
from .models import Post
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, View, DetailView


# Create your views here.

def index(request):
    posts = Post.objects.all()[1:]
    latest = Post.objects.all()[0]
    context = {
        'posts' : posts,
        'latest' : latest
    }
    return render(request,'core/index.html', context)

class PostView(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'core/post.html'
    

def verify(request):
    return render(request, 'core/verify.html')

from django.core.mail import send_mail
from magazine.settings import EMAIL_HOST_USER
from django.template.loader import render_to_string
from django.utils.html import strip_tags

def register(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = request.user
            new_user = authenticate(username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'],
            )
            login(request, new_user)
            email = form.cleaned_data.get('email')
            subject = 'Hello there!'
            message = 'Thank you for signing up to the OSC School Magazine'
            recipient = email
            username = form.cleaned_data.get('username')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            act_key = user.profile.activation_key
            x = {
                'user':request.user,
                'key':act_key
            }
            html_message = render_to_string('core/email.html', x)
            plain_message = strip_tags(html_message)
            send_mail(subject, plain_message, EMAIL_HOST_USER, [recipient], html_message=html_message, fail_silently=False)
            print(f'Key is: {act_key}')
            return redirect('core:verify')
    else:
        form = ProfileForm()
    return render(request,'core/register.html', {'form' : form})

def logout_user(request):
    logout(request)
    return redirect('core:index')

from django.http import JsonResponse
from django.contrib.auth.models import User

def validate_username(request):
    username = request.GET.get('username', None)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists(),
        'exists': User.objects.filter(username__iexact=username).exists()
    }
    if data['is_taken']:
        data['message'] = 'Someone with that username already exists!'
    elif data['exists'] == False:
        data['message'] = "That username doesn't exist"
    return JsonResponse(data)

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Orbost Secondary College Magazine</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script>
    </script>
</head>
<body>
    <style>
        .user-menu {
            position: relative;
            transition: 0.2s ease-in-out;
        }
        .user-menu__options {
            background: white;
            box-shadow: 0px 2px 15px 0px rgb(80, 80, 80);
            position: absolute;
            color: black;
            text-align: center;
            padding: 5%;
            display: none;
            transition: 0.2s ease-in-out;
        }
        .user-menu__options a {
            color: black;
            display: block;
            padding: 10px;
            font-size: 1.2rem;
        }
        .user-menu:hover .user-menu__options {
            display: block;
        }
    </style>
    <nav class="nav">
        <div class="nav__element nav__heading">
            <a id="osc-nav-he" href="{% url 'core:index' %}"><h1 id="osc-nav-he">OSC Magazine</h1></a>
        </div>
        <div class="nav__element nav__profile-section">
            <span><i style="margin-top:8px;margin-right: 3px;" class="feather-icon" data-feather="search"></i></span><input type="search" placeholder="Search Site">
            {% if user.is_authenticated %}
            <div class="user-menu">
                <button class="btn btn__link--dark" id="profile-nav-stuff"><i class="feather-icon" data-feather="user"></i> {{ user }}</button>
                <div class="user-menu__options">
                    <a href="#">Make Post</a>
                    <span id="everything-theme">
                        <a title="Double Click To Change" onclick="changeTheme()" id="theme-changer" href="#"><span data-feather="moon"></span> Theme</a>
                    </span>
                    {% if user.is_superuser %}
                    <a href="{% url 'admin:index' %}"><span style="font-size: 0.1em;" data-feather="database"></span> Admin Panel</a>
                    {% endif %}
                    <a href="{% url 'core:logout' %}">Logout</a>
                </div>
            </div>
            {% else %}
            <button id="register-btn" class="btn btn__link--dark"><i class="feather-icon" data-feather="edit-2"></i> Sign Up To Write</button>
            {% endif %}
            <button class="btn btn__primary--dark"><i class="feather-icon" data-feather="archive"></i> View Archive</button>
        </div>
    </nav> 

    {% block content %} {% endblock %}


    <script src="{% static 'js/app.js' %}"></script>
    <script>
        document.getElementById('register-btn').addEventListener('click', () => {
            window.location = "{% url 'core:register' %}"
        });
    </script>
</body>
</html>

core/templates/core/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Questrial&display=swap" rel="stylesheet">
</head>
<body>
    <link href="https://fonts.googleapis.com/css2?family=Questrial&display=swap" rel="stylesheet">
    <div style="text-align: center;margin: 0 auto; background: white;box-shadow: 0px 0px 20px 0px #e2e2e2;padding: 32px; width: 80%;font-family: 'Questrial', sans-serif; " class="container">
        <h1>Thank you, {{ user }} for signing up to the OSC Magazine!</h1>
        <h2>Please verify your email!</h2>
        <button style="padding:10px 20px; color: white; cursor: pointer; border-radius: 4px; background: blue;border: none;outline: none;font-family: 'Questrial', sans-serif;">Verify</button>
        <small>Activation key: {{ key }}</small>
    </div>
</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}

<div class="oops"></div>
<section class="articles">
    <div class="articles__featured">
        <img id="featured-img" src="{% static 'images/bg.jpg' %}" alt="Featured Article">
        <h1 class="articles__title--featured articles__link"><a class="global-link" id="fea" href="{% url 'core:post' slug=latest.slug %}">{{ latest.title }}</a></h1>
        <p class="articles__sub articles__link"><span class="articles__author">By <span style="font-weight: 700;">{{ latest.author }}</span></p>
    </div>
    <!-- <div class="articles__tags">
        <h1>Read more tags</h1>
            <div class="tags__tag">
                <p>Art</p>
            </div>
            <div class="tags__tag">
                <p>Art</p>
            </div>
            <div class="tags__tag">
                <p>Art</p>
            </div>
    </div> -->
    <div class="">
        
    </div>
    <div class="articles__special">
        <h1 style="margin-bottom: 20px;"> <span data-feather="loader"></span> Special Posts</h1>
        <div class="articles__special-container">
            <div class="articles__post">
                <img src="{% static 'images/ThumbnailOSCMag.png' %}" alt="Sub Articles">
            </div>
            <div class="articles__post">
                <img src="{% static 'images/ThumbnailOSCMag.png' %}" alt="Sub Articles">
            </div>
        </div>
    </div>
    <div class="articles__sub">
        {% for post in posts %}
        <div class="articles__article">
            <img src="{% static 'images/ThumbnailOSCMag.png' %}" alt="Sub Articles">
            <h1 class="articles__title articles__link"><a class="global-link" href="{% url 'core:post' slug=post.slug %}">{{ post.title }}</a></h1>
        </div>
        {% endfor %}
    </div>
</section>

<!-- <div class="articles__search">
    <h1 style="margin-bottom: 20px;"> <span data-feather="loader"></span> Can't find what you're looking for?</h1> <span><i style="margin-top:8px;margin-right: 3px;" class="feather-icon" data-feather="search"></i></span><input type="search" placeholder="Search Site">
</div> -->
<script>
    document.getElementById('fea').addEventListener('click', () => {
        doc = document.getElementsByClassName('oops')[0]
        console.log('Clicked')
        $(document.body).load("{% url 'core:post' slug=latest.slug %}")
    })
</script>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}
{% load static %}

{% load i18n %}
{% load account socialaccount %}
{% block content %}
<style>
    .error {
        background: red;
        padding: 20px;
        color: white;
        margin-bottom: 50px;
    }
</style>
{% get_providers as socialaccount_providers %}
<div class="socialaccount_ballot">

    <ul class="socialaccount_providers">
      {% include "socialaccount/snippets/provider_list.html" with process="login" %}
    </ul>
  
    <div class="login-or">{% trans 'or' %}</div>
  
  </div>
<form method="POST" action="{% url 'core:login' %}">
    
    <div style="display: none;" class="error">
        <p id="error-msg"></p>
    </div>
    <small id="ava" style="display: none;">Username Good!</small>
    {% csrf_token %}
    <input id="username-input" required aria-required="true" type="text" name="username" placeholder="Username">
    <br>
    <input required aria-required="true" type="password" name="password" placeholder="Password">
    <br>
    <input type="submit" value="Login">
</form>
<small><a href="{% url 'core:register' %}">Register Instead</a></small>

<script>
$('#username-input').keyup(function(e) {
    var username = $(this).val();
    $.ajax({
        url: '/ajax/validate_username/',
        data: {
            'username': username
        },
        dataType: "json",
        success: function(data) {
            if (!data.exists) {
                $(".error").css('display','block')
                $("#ava").css('display','none');
                $("#error-msg").html(data.message)
            } else {
                $("#ava").css('display','block');
                $(".error").css('display','none')
            }
        }
    })
})
</script>

{% endblock %}

core/templates/core/post.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

<h1>{{ post.title }}</h1>
<p>Posted by: {{ post.author }}</p>
<p>{{ post.content }}</p>

{% endblock %}

core/templates/core/register.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

<form method="POST">
    <div style="display: none;" class="error">
        <p id="error-msg"></p>
    </div>
    {% csrf_token %}
    {{ form }}
    <button type="submit">Register</button>
</form>

<small><a href="{% url 'core:login' %}">Login Instead</a></small>

<style>
    .error {
        background: red;
        padding: 20px;
        color: white;
        margin-bottom: 50px;
    }
</style>

<script>
    $("#id_username").keyup(function (e) {
        var username = $(this).val();
        $.ajax({
          url: '/ajax/validate_username/',
          data: {
            'username': username
          },
          dataType: 'json',
          success: function (data) {
            if (data.is_taken) {
                console.log('YES');
                $(".error").css('display','block')
                $("#error-msg").html(data.message)
            } else {
                console.log('NO');
                $(".error").css('display','none')
            }
          },
          error: function(jqXhr) {
            console.log('YES')
            alert("ERROR")
          }
        });
  
      });
</script>

{% endblock %}

core/templates/core/verify.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

<h1>Please check your emails. We sent you something</h1>
<h2>This page will redirect in 10 seconds</h2>

<script>
    setTimeout(function() {
        console.log("THIS SHOULD WORK")
        window.location.replace("{% url 'core:index' %}")
    },10000)
</script>

{% endblock %}